version: '3'
services:
  emqx:
    image: emqx/emqx:5.3.2
    container_name: emqx
    restart: always
    ports:
      - '1883:1883'
      - '8083:8083'
      - '8883:8883'
      - '8084:8084'
      - '18083:18083'
    environment:
      - EMQX_NAME=emqx
  postgres:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=emqx
